server:
  port: 8801

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    register-with-eureka: true #注册到Eureka的注册中⼼
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://r1:7001/eureka/ #配置注册中⼼地址
info:
  remark: admin-consumer

spring:
  application:
    name: consumer-admin-8801