server:
  port: 8888
---
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/ #配置注册中⼼地址
---
info:
  remark: 这是一个班级信息消费者
  author: liyan
---
spring:
  application:
    name: consumer-banji-8888
