server:
  port: 8802
---
spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://localhost:3306/florist?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/
---
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
---
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true #注册到Eureka的注册中⼼
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:7002/eureka/ #配置注册中⼼地址
---
info:
  remark: 这是一个信息服务，提供了增删改查
  author: liyan
---
ribbon:
  eureka:
    enabled: true
---
spring:
  main:
    allow-bean-definition-overriding: true