server:
  port: 8802
---
eureka:
  instance:
    instance-id: ${spring.application.name}-${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ #配置注册中⼼地址
---
info:
  remark: 这是一个用户信息消费者
  author: liyan
---
spring:
  application:
    name: consumer-user
---
spring:
  thymeleaf:
    suffix: .html
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
    cache: false