server:
  port: 7001
---
spring:
  application:
    name: eureka-server
---
eureka:
  instance:
    hostname: r1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
