server:
  port: 8201
---
spring:
  application:
    name: proxy-zuul
---
eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7001/eureka/
---
info:
  remark: 网关服务Zuul
---
zuul:
  routes:
    provider-banji:
      path: /providerBanji/**
  ignored-services: provider-banji #关闭默认路由配置